// This file is auto-generated by @hey-api/openapi-ts

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const JobCreateSchema = {
    properties: {
        source_name: {
            type: 'string',
            title: 'Source Name'
        },
        library_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Library Id'
        },
        dry_run: {
            type: 'boolean',
            title: 'Dry Run',
            default: true
        },
        overwrite_existing: {
            type: 'boolean',
            title: 'Overwrite Existing',
            default: false
        }
    },
    type: 'object',
    required: ['source_name'],
    title: 'JobCreate'
} as const;

export const JobPublicSchema = {
    properties: {
        source_name: {
            type: 'string',
            title: 'Source Name'
        },
        library_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Library Id'
        },
        dry_run: {
            type: 'boolean',
            title: 'Dry Run',
            default: true
        },
        overwrite_existing: {
            type: 'boolean',
            title: 'Overwrite Existing',
            default: false
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'pending'
        },
        total: {
            type: 'integer',
            title: 'Total',
            default: 0
        },
        processed: {
            type: 'integer',
            title: 'Processed',
            default: 0
        },
        written: {
            type: 'integer',
            title: 'Written',
            default: 0
        },
        skipped: {
            type: 'integer',
            title: 'Skipped',
            default: 0
        },
        errors: {
            type: 'integer',
            title: 'Errors',
            default: 0
        },
        message: {
            type: 'string',
            title: 'Message',
            default: ''
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['source_name', 'id', 'created_at', 'updated_at'],
    title: 'JobPublic'
} as const;

export const LibraryInfoSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            type: 'string',
            title: 'Type',
            default: 'music'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'LibraryInfo'
} as const;

export const SourceCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        base_url: {
            type: 'string',
            title: 'Base Url'
        },
        token: {
            type: 'string',
            title: 'Token'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        },
        user_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['name', 'type', 'base_url', 'token'],
    title: 'SourceCreate'
} as const;

export const SourcePublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        base_url: {
            type: 'string',
            title: 'Base Url'
        },
        token: {
            type: 'string',
            title: 'Token'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        },
        user_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'type', 'base_url', 'token', 'id', 'created_at'],
    title: 'SourcePublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;