// This file is auto-generated by @hey-api/openapi-ts

export const AppConfigSchema = {
    properties: {
        timezone: {
            type: 'string',
            title: 'Timezone'
        }
    },
    type: 'object',
    required: ['timezone'],
    title: 'AppConfig'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const JobCreateSchema = {
    properties: {
        source_name: {
            type: 'string',
            title: 'Source Name'
        },
        library_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Library Id'
        },
        dry_run: {
            type: 'boolean',
            title: 'Dry Run',
            default: true
        },
        write_mode: {
            type: 'string',
            enum: ['skip', 'fix', 'overwrite'],
            title: 'Write Mode',
            default: 'fix'
        }
    },
    type: 'object',
    required: ['source_name'],
    title: 'JobCreate'
} as const;

export const JobLogSchema = {
    properties: {
        log: {
            type: 'string',
            title: 'Log'
        }
    },
    type: 'object',
    required: ['log'],
    title: 'JobLog'
} as const;

export const JobPublicSchema = {
    properties: {
        source_name: {
            type: 'string',
            title: 'Source Name'
        },
        library_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Library Id'
        },
        dry_run: {
            type: 'boolean',
            title: 'Dry Run',
            default: true
        },
        write_mode: {
            type: 'string',
            title: 'Write Mode',
            default: 'fix'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'pending'
        },
        total: {
            type: 'integer',
            title: 'Total',
            default: 0
        },
        processed: {
            type: 'integer',
            title: 'Processed',
            default: 0
        },
        written: {
            type: 'integer',
            title: 'Written',
            default: 0
        },
        skipped: {
            type: 'integer',
            title: 'Skipped',
            default: 0
        },
        errors: {
            type: 'integer',
            title: 'Errors',
            default: 0
        },
        message: {
            type: 'string',
            title: 'Message',
            default: ''
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['source_name', 'id', 'created_at', 'updated_at'],
    title: 'JobPublic'
} as const;

export const JobsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/JobPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'JobsPublic'
} as const;

export const LibraryInfoSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            type: 'string',
            title: 'Type',
            default: 'music'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'LibraryInfo'
} as const;

export const PathMappingCreateSchema = {
    properties: {
        remote_path: {
            type: 'string',
            title: 'Remote Path'
        },
        local_path: {
            type: 'string',
            title: 'Local Path'
        }
    },
    type: 'object',
    required: ['remote_path', 'local_path'],
    title: 'PathMappingCreate'
} as const;

export const PathMappingPublicSchema = {
    properties: {
        remote_path: {
            type: 'string',
            title: 'Remote Path'
        },
        local_path: {
            type: 'string',
            title: 'Local Path'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['remote_path', 'local_path', 'id'],
    title: 'PathMappingPublic'
} as const;

export const PlexPinCreateSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        oauth_url: {
            type: 'string',
            title: 'Oauth Url'
        }
    },
    type: 'object',
    required: ['id', 'oauth_url'],
    title: 'PlexPinCreate'
} as const;

export const PlexPinStatusSchema = {
    properties: {
        authenticated: {
            type: 'boolean',
            title: 'Authenticated'
        },
        token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token'
        }
    },
    type: 'object',
    required: ['authenticated'],
    title: 'PlexPinStatus'
} as const;

export const PlexServerConnectionSchema = {
    properties: {
        uri: {
            type: 'string',
            title: 'Uri'
        },
        local: {
            type: 'boolean',
            title: 'Local'
        }
    },
    type: 'object',
    required: ['uri', 'local'],
    title: 'PlexServerConnection'
} as const;

export const PlexServerOptionSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        connections: {
            items: {
                '$ref': '#/components/schemas/PlexServerConnection'
            },
            type: 'array',
            title: 'Connections'
        }
    },
    type: 'object',
    required: ['name', 'connections'],
    title: 'PlexServerOption'
} as const;

export const ScheduleUpdateSchema = {
    properties: {
        schedule_cron: {
            type: 'string',
            title: 'Schedule Cron'
        }
    },
    type: 'object',
    required: ['schedule_cron'],
    title: 'ScheduleUpdate'
} as const;

export const SourceCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        base_url: {
            type: 'string',
            title: 'Base Url'
        },
        token: {
            type: 'string',
            title: 'Token'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        },
        library_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Library Id'
        },
        schedule_cron: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Schedule Cron'
        },
        path_mappings: {
            items: {
                '$ref': '#/components/schemas/PathMappingCreate'
            },
            type: 'array',
            title: 'Path Mappings',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'type', 'base_url', 'token'],
    title: 'SourceCreate'
} as const;

export const SourcePublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        base_url: {
            type: 'string',
            title: 'Base Url'
        },
        token: {
            type: 'string',
            title: 'Token'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        },
        library_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Library Id'
        },
        schedule_cron: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Schedule Cron'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        },
        next_run_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Run At'
        },
        last_run_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Run At'
        },
        path_mappings: {
            items: {
                '$ref': '#/components/schemas/PathMappingPublic'
            },
            type: 'array',
            title: 'Path Mappings',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'type', 'base_url', 'token', 'id', 'created_at'],
    title: 'SourcePublic'
} as const;

export const SourceTestRequestSchema = {
    properties: {
        type: {
            type: 'string',
            title: 'Type'
        },
        base_url: {
            type: 'string',
            title: 'Base Url'
        },
        token: {
            type: 'string',
            title: 'Token'
        }
    },
    type: 'object',
    required: ['type', 'base_url', 'token'],
    title: 'SourceTestRequest'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;