// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { JobsListJobsResponse, JobsCreateJobData, JobsCreateJobResponse, JobsGetJobData, JobsGetJobResponse, SourcesListSourcesResponse, SourcesAddSourceData, SourcesAddSourceResponse, SourcesDeleteSourceData, SourcesDeleteSourceResponse, SourcesTestSourceData, SourcesTestSourceResponse, SourcesListLibrariesData, SourcesListLibrariesResponse, UtilsHealthCheckResponse } from './types.gen';

export class JobsService {
    /**
     * List Jobs
     * @returns JobPublic Successful Response
     * @throws ApiError
     */
    public static listJobs(): CancelablePromise<JobsListJobsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/jobs/'
        });
    }
    
    /**
     * Create Job
     * @param data The data for the request.
     * @param data.requestBody
     * @returns JobPublic Successful Response
     * @throws ApiError
     */
    public static createJob(data: JobsCreateJobData): CancelablePromise<JobsCreateJobResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/jobs/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Job
     * @param data The data for the request.
     * @param data.jobId
     * @returns JobPublic Successful Response
     * @throws ApiError
     */
    public static getJob(data: JobsGetJobData): CancelablePromise<JobsGetJobResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/jobs/{job_id}',
            path: {
                job_id: data.jobId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SourcesService {
    /**
     * List Sources
     * @returns SourcePublic Successful Response
     * @throws ApiError
     */
    public static listSources(): CancelablePromise<SourcesListSourcesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sources/'
        });
    }
    
    /**
     * Add Source
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SourcePublic Successful Response
     * @throws ApiError
     */
    public static addSource(data: SourcesAddSourceData): CancelablePromise<SourcesAddSourceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sources/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Source
     * @param data The data for the request.
     * @param data.name
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteSource(data: SourcesDeleteSourceData): CancelablePromise<SourcesDeleteSourceResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/sources/{name}',
            path: {
                name: data.name
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Source
     * @param data The data for the request.
     * @param data.name
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static testSource(data: SourcesTestSourceData): CancelablePromise<SourcesTestSourceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sources/{name}/test',
            path: {
                name: data.name
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Libraries
     * @param data The data for the request.
     * @param data.name
     * @returns LibraryInfo Successful Response
     * @throws ApiError
     */
    public static listLibraries(data: SourcesListLibrariesData): CancelablePromise<SourcesListLibrariesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sources/{name}/libraries',
            path: {
                name: data.name
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}