// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { JobsCreateJobData, JobsCreateJobResponse, JobsListJobsData, JobsListJobsResponse, JobsGetJobsLogData, JobsGetJobsLogResponse, JobsGetJobData, JobsGetJobResponse, JobsCancelJobData, JobsCancelJobResponse, SourcesListSourcesResponse, SourcesAddSourceData, SourcesAddSourceResponse, SourcesDeleteSourceData, SourcesDeleteSourceResponse, SourcesSetScheduleData, SourcesSetScheduleResponse, SourcesClearScheduleData, SourcesClearScheduleResponse, SourcesTestSourceData, SourcesTestSourceResponse, SourcesTestConnectionData, SourcesTestConnectionResponse, SourcesListLibrariesForConnectionData, SourcesListLibrariesForConnectionResponse, SourcesCreatePlexPinResponse, SourcesCheckPlexPinData, SourcesCheckPlexPinResponse, SourcesListPlexServersData, SourcesListPlexServersResponse, SourcesListLibrariesData, SourcesListLibrariesResponse, UtilsHealthCheckResponse } from './types.gen';

export class JobsService {
    /**
     * Create Job
     * @param data The data for the request.
     * @param data.requestBody
     * @returns JobPublic Successful Response
     * @throws ApiError
     */
    public static createJob(data: JobsCreateJobData): CancelablePromise<JobsCreateJobResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/jobs/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Jobs
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns JobsPublic Successful Response
     * @throws ApiError
     */
    public static listJobs(data: JobsListJobsData = {}): CancelablePromise<JobsListJobsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/jobs/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Jobs Log
     * @param data The data for the request.
     * @param data.jobId
     * @returns JobLog Successful Response
     * @throws ApiError
     */
    public static getJobsLog(data: JobsGetJobsLogData = {}): CancelablePromise<JobsGetJobsLogResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/jobs/log',
            query: {
                job_id: data.jobId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Job
     * @param data The data for the request.
     * @param data.jobId
     * @returns JobPublic Successful Response
     * @throws ApiError
     */
    public static getJob(data: JobsGetJobData): CancelablePromise<JobsGetJobResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/jobs/{job_id}',
            path: {
                job_id: data.jobId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Cancel Job
     * @param data The data for the request.
     * @param data.jobId
     * @returns JobPublic Successful Response
     * @throws ApiError
     */
    public static cancelJob(data: JobsCancelJobData): CancelablePromise<JobsCancelJobResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/jobs/{job_id}/cancel',
            path: {
                job_id: data.jobId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SourcesService {
    /**
     * List Sources
     * @returns SourcePublic Successful Response
     * @throws ApiError
     */
    public static listSources(): CancelablePromise<SourcesListSourcesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sources/'
        });
    }
    
    /**
     * Add Source
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SourcePublic Successful Response
     * @throws ApiError
     */
    public static addSource(data: SourcesAddSourceData): CancelablePromise<SourcesAddSourceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sources/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Source
     * @param data The data for the request.
     * @param data.name
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static deleteSource(data: SourcesDeleteSourceData): CancelablePromise<SourcesDeleteSourceResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/sources/{name}',
            path: {
                name: data.name
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Set Schedule
     * @param data The data for the request.
     * @param data.name
     * @param data.requestBody
     * @returns SourcePublic Successful Response
     * @throws ApiError
     */
    public static setSchedule(data: SourcesSetScheduleData): CancelablePromise<SourcesSetScheduleResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/sources/{name}/schedule',
            path: {
                name: data.name
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Clear Schedule
     * @param data The data for the request.
     * @param data.name
     * @returns SourcePublic Successful Response
     * @throws ApiError
     */
    public static clearSchedule(data: SourcesClearScheduleData): CancelablePromise<SourcesClearScheduleResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/sources/{name}/schedule',
            path: {
                name: data.name
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Source
     * @param data The data for the request.
     * @param data.name
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static testSource(data: SourcesTestSourceData): CancelablePromise<SourcesTestSourceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sources/{name}/test',
            path: {
                name: data.name
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Connection
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static testConnection(data: SourcesTestConnectionData): CancelablePromise<SourcesTestConnectionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sources/test',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Libraries For Connection
     * @param data The data for the request.
     * @param data.requestBody
     * @returns LibraryInfo Successful Response
     * @throws ApiError
     */
    public static listLibrariesForConnection(data: SourcesListLibrariesForConnectionData): CancelablePromise<SourcesListLibrariesForConnectionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sources/libraries',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Plex Pin
     * @returns PlexPinCreate Successful Response
     * @throws ApiError
     */
    public static createPlexPin(): CancelablePromise<SourcesCreatePlexPinResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sources/plex/oauth/pin'
        });
    }
    
    /**
     * Check Plex Pin
     * @param data The data for the request.
     * @param data.pinId
     * @returns PlexPinStatus Successful Response
     * @throws ApiError
     */
    public static checkPlexPin(data: SourcesCheckPlexPinData): CancelablePromise<SourcesCheckPlexPinResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sources/plex/oauth/pin/{pin_id}',
            path: {
                pin_id: data.pinId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Plex Servers
     * @param data The data for the request.
     * @param data.token
     * @returns PlexServerOption Successful Response
     * @throws ApiError
     */
    public static listPlexServers(data: SourcesListPlexServersData): CancelablePromise<SourcesListPlexServersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sources/plex/oauth/servers',
            query: {
                token: data.token
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Libraries
     * @param data The data for the request.
     * @param data.name
     * @returns LibraryInfo Successful Response
     * @throws ApiError
     */
    public static listLibraries(data: SourcesListLibrariesData): CancelablePromise<SourcesListLibrariesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sources/{name}/libraries',
            path: {
                name: data.name
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}