// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type JobCreate = {
    source_name: string;
    library_id?: (string | null);
    dry_run?: boolean;
    overwrite_existing?: boolean;
};

export type JobPublic = {
    source_name: string;
    library_id?: (string | null);
    dry_run?: boolean;
    overwrite_existing?: boolean;
    status?: string;
    total?: number;
    processed?: number;
    written?: number;
    skipped?: number;
    errors?: number;
    message?: string;
    id: string;
    created_at: string;
    updated_at: string;
};

export type LibraryInfo = {
    id: string;
    name: string;
    type?: string;
};

export type PathMappingCreate = {
    remote_path: string;
    local_path: string;
};

export type PathMappingPublic = {
    remote_path: string;
    local_path: string;
    id: number;
};

export type ScheduleUpdate = {
    schedule_cron: string;
    schedule_enabled?: boolean;
};

export type SourceCreate = {
    name: string;
    type: string;
    base_url: string;
    token: string;
    enabled?: boolean;
    user_id?: (string | null);
    schedule_cron?: (string | null);
    schedule_enabled?: boolean;
    path_mappings?: Array<PathMappingCreate>;
};

export type SourcePublic = {
    name: string;
    type: string;
    base_url: string;
    token: string;
    enabled?: boolean;
    user_id?: (string | null);
    schedule_cron?: (string | null);
    schedule_enabled?: boolean;
    id: number;
    created_at: string;
    next_run_at?: (string | null);
    last_run_at?: (string | null);
    path_mappings?: Array<PathMappingPublic>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type JobsListJobsResponse = (Array<JobPublic>);

export type JobsCreateJobData = {
    requestBody: JobCreate;
};

export type JobsCreateJobResponse = (JobPublic);

export type JobsGetJobData = {
    jobId: string;
};

export type JobsGetJobResponse = (JobPublic);

export type SourcesListSourcesResponse = (Array<SourcePublic>);

export type SourcesAddSourceData = {
    requestBody: SourceCreate;
};

export type SourcesAddSourceResponse = (SourcePublic);

export type SourcesDeleteSourceData = {
    name: string;
};

export type SourcesDeleteSourceResponse = ({
    [key: string]: (boolean);
});

export type SourcesSetScheduleData = {
    name: string;
    requestBody: ScheduleUpdate;
};

export type SourcesSetScheduleResponse = (SourcePublic);

export type SourcesClearScheduleData = {
    name: string;
};

export type SourcesClearScheduleResponse = (SourcePublic);

export type SourcesTestSourceData = {
    name: string;
};

export type SourcesTestSourceResponse = ({
    [key: string]: unknown;
});

export type SourcesListLibrariesData = {
    name: string;
};

export type SourcesListLibrariesResponse = (Array<LibraryInfo>);

export type UtilsHealthCheckResponse = (boolean);