"""add source schedule fields

Revision ID: 392e56924af0
Revises: d8e60c6d16ca
Create Date: 2026-08-24 16:36:34.613258

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '392e56924af0'
down_revision = 'd8e60c6d16ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('schedule_cron', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('source', sa.Column('schedule_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('source', sa.Column('next_run_at', sa.DateTime(), nullable=True))
    op.add_column('source', sa.Column('last_run_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'last_run_at')
    op.drop_column('source', 'next_run_at')
    op.drop_column('source', 'schedule_enabled')
    op.drop_column('source', 'schedule_cron')
    # ### end Alembic commands ###
