"""add source path mappings table

Revision ID: aa49782b4b7f
Revises: 392e56924af0
Create Date: 2026-08-24 19:02:54.601145

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aa49782b4b7f'
down_revision = '392e56924af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pathmapping',
    sa.Column('remote_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pathmapping_source_id'), 'pathmapping', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pathmapping_source_id'), table_name='pathmapping')
    op.drop_table('pathmapping')
    # ### end Alembic commands ###
